"""
Standardized definitions for all 56 skills from awesome-claude-skills-master.

Each skill definition follows this schema:
{
    "id":               str  — unique slug
    "name":             str  — display name
    "description":      str  — what it does
    "category":         str  — top-level bucket
    "subcategory":      str  — finer grouping
    "inputs":           list — what it needs from the user
    "outputs":          list — what it produces
    "execution_type":   str  — "prompt" | "script" | "hybrid"
    "dependencies":     list — external tools / packages required
    "trigger_keywords": list — words that auto-activate this skill
    "agent_affinity":   list — which agents work best with it
    "folder":           str  — subfolder inside awesome-claude-skills-master
    "scripts":          list — runnable script paths (relative to folder)
    "has_context":      bool — whether SKILL.md provides useful LLM context
    "active":           bool — enabled by default
}
"""

from pathlib import Path

# Root of the skills collection (relative to CWD = executive-agent-app/)
SKILLS_ROOT = Path("../awesome-claude-skills-master")

ALL_SKILLS: list[dict] = [
    # ─────────────────────────── CONTENT CREATION ────────────────────────────
    {
        "id":           "artifacts-builder",
        "name":         "Artifacts Builder",
        "description":  "Build rich React/TypeScript HTML artifacts with shadcn/ui — "
                        "initialises Vite projects, bundles to single HTML file.",
        "category":     "content",
        "subcategory":  "frontend",
        "inputs":       ["description", "components_needed", "styling_preferences"],
        "outputs":      ["html_artifact", "react_project"],
        "execution_type": "hybrid",
        "dependencies": ["node", "npm"],
        "trigger_keywords": [
            "artifact", "react", "shadcn", "vite", "frontend component",
            "html artifact", "build ui component", "render component",
            "interactive ui", "web artifact", "rich html",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "artifacts-builder",
        "scripts":      ["scripts/init-artifact.sh", "scripts/bundle-artifact.sh"],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "brand-guidelines",
        "name":         "Brand Guidelines",
        "description":  "Apply Anthropic's official brand colors and typography to any artifact or design.",
        "category":     "content",
        "subcategory":  "design",
        "inputs":       ["artifact_or_text"],
        "outputs":      ["branded_artifact"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "brand", "brand color", "brand style", "anthropic brand",
            "brand identity", "brand guidelines", "official colors",
            "brand typography", "poppins", "lora font",
        ],
        "agent_affinity": ["content", "coder"],
        "folder":       "brand-guidelines",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "canvas-design",
        "name":         "Canvas Design",
        "description":  "Create museum-quality visual designs: posters, infographics, PDFs using 80+ premium fonts.",
        "category":     "content",
        "subcategory":  "design",
        "inputs":       ["concept", "dimensions", "style_preferences"],
        "outputs":      ["design_artifact", "pdf", "png"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "design", "poster", "infographic", "visual", "artwork",
            "creative design", "pdf design", "graphic design", "aesthetic",
            "beautiful design", "visual design", "layout", "typography",
            "illustration", "banner", "flyer", "brochure",
        ],
        "agent_affinity": ["content"],
        "folder":       "canvas-design",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "changelog-generator",
        "name":         "Changelog Generator",
        "description":  "Auto-generate user-facing changelogs from git commit history.",
        "category":     "content",
        "subcategory":  "documentation",
        "inputs":       ["git_commits_or_log", "version_number"],
        "outputs":      ["changelog_md", "release_notes"],
        "execution_type": "prompt",
        "dependencies": ["git"],
        "trigger_keywords": [
            "changelog", "release notes", "version history", "what changed",
            "release log", "git history", "commit history", "release summary",
            "what's new", "update notes",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "changelog-generator",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "slack-gif-creator",
        "name":         "Slack GIF Creator",
        "description":  "Create animated GIFs optimised for Slack using Python animation primitives.",
        "category":     "content",
        "subcategory":  "media",
        "inputs":       ["animation_concept", "dimensions", "duration"],
        "outputs":      ["gif_file"],
        "execution_type": "hybrid",
        "dependencies": ["pillow", "imageio", "numpy"],
        "trigger_keywords": [
            "gif", "animated gif", "slack gif", "animation", "create gif",
            "make gif", "animate", "animated image", "loop animation",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "slack-gif-creator",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "theme-factory",
        "name":         "Theme Factory",
        "description":  "Apply 10 professional themes (arctic-frost, midnight-galaxy, etc.) to slides, docs, HTML.",
        "category":     "content",
        "subcategory":  "design",
        "inputs":       ["artifact_or_content", "theme_name"],
        "outputs":      ["themed_artifact"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "theme", "color theme", "apply theme", "dark theme", "light theme",
            "midnight galaxy", "arctic frost", "ocean depths", "forest canopy",
            "golden hour", "desert rose", "botanical", "sunset", "styling",
            "visual theme", "design theme",
        ],
        "agent_affinity": ["content", "coder"],
        "folder":       "theme-factory",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── RESUME & CAREERS ────────────────────────────
    {
        "id":           "tailored-resume-generator",
        "name":         "Tailored Resume Generator",
        "description":  "Analyse job descriptions and generate ATS-optimised tailored resumes.",
        "category":     "career",
        "subcategory":  "job_search",
        "inputs":       ["job_description", "current_resume_or_profile"],
        "outputs":      ["tailored_resume", "cover_letter"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "resume", "cv", "job application", "tailor resume", "customize resume",
            "cover letter", "ats resume", "apply job", "job resume",
            "resume for job", "optimize resume",
        ],
        "agent_affinity": ["job", "content"],
        "folder":       "tailored-resume-generator",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── BUSINESS / SALES ────────────────────────────
    {
        "id":           "competitive-ads-extractor",
        "name":         "Competitive Ads Extractor",
        "description":  "Extract and analyse competitor ads from Facebook, LinkedIn ad libraries.",
        "category":     "business",
        "subcategory":  "marketing",
        "inputs":       ["competitor_name", "platform", "industry"],
        "outputs":      ["ads_analysis_report", "insights"],
        "execution_type": "hybrid",
        "dependencies": ["browser"],
        "trigger_keywords": [
            "competitor ads", "ad analysis", "facebook ads", "linkedin ads",
            "ad library", "competitive ads", "ad research", "competitor marketing",
            "spy ads", "what competitors advertise", "competitor strategy",
        ],
        "agent_affinity": ["browser", "sales"],
        "folder":       "competitive-ads-extractor",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "domain-name-brainstormer",
        "name":         "Domain Name Brainstormer",
        "description":  "Generate creative domain name ideas and check availability across multiple TLDs.",
        "category":     "business",
        "subcategory":  "branding",
        "inputs":       ["business_concept", "industry", "target_audience"],
        "outputs":      ["domain_suggestions", "availability_report"],
        "execution_type": "hybrid",
        "dependencies": ["browser"],
        "trigger_keywords": [
            "domain name", "domain ideas", "check domain", "website name",
            "brand name", "startup name", "available domain", "domain availability",
            ".com", ".io", ".ai domain", "company name ideas",
        ],
        "agent_affinity": ["browser", "sales"],
        "folder":       "domain-name-brainstormer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "lead-research-assistant",
        "name":         "Lead Research Assistant",
        "description":  "Identify, research, and qualify high-value leads for any product or service.",
        "category":     "business",
        "subcategory":  "sales",
        "inputs":       ["product_or_service", "target_market", "ideal_customer_profile"],
        "outputs":      ["lead_list", "qualification_report", "contact_strategy"],
        "execution_type": "hybrid",
        "dependencies": ["browser"],
        "trigger_keywords": [
            "lead research", "find leads", "prospect", "lead generation",
            "target companies", "sales prospect", "lead qualification",
            "find customers", "potential clients", "b2b leads",
            "customer research",
        ],
        "agent_affinity": ["browser", "sales"],
        "folder":       "lead-research-assistant",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "twitter-algorithm-optimizer",
        "name":         "Twitter/X Algorithm Optimizer",
        "description":  "Rewrite and optimise tweets for maximum reach using Twitter algorithm insights.",
        "category":     "business",
        "subcategory":  "social_media",
        "inputs":       ["tweet_text", "target_audience", "goal"],
        "outputs":      ["optimised_tweet", "engagement_analysis"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "twitter", "tweet", "x.com post", "optimize tweet",
            "twitter engagement", "viral tweet", "rewrite tweet",
            "twitter algorithm", "improve tweet", "x post",
            "social media post twitter",
        ],
        "agent_affinity": ["content", "sales"],
        "folder":       "twitter-algorithm-optimizer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── AUTOMATION / FILES ──────────────────────────
    {
        "id":           "file-organizer",
        "name":         "File Organizer",
        "description":  "Intelligently organise files — find duplicates, sort by type/date, clean up folders.",
        "category":     "automation",
        "subcategory":  "files",
        "inputs":       ["folder_path", "organisation_scheme"],
        "outputs":      ["organised_folder", "cleanup_report"],
        "execution_type": "hybrid",
        "dependencies": [],
        "trigger_keywords": [
            "organize files", "organise files", "clean up files", "sort files",
            "file organization", "downloads folder", "tidy up", "find duplicates",
            "file cleanup", "sort documents", "clean desktop",
        ],
        "agent_affinity": ["desktop", "coder"],
        "folder":       "file-organizer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "invoice-organizer",
        "name":         "Invoice Organizer",
        "description":  "Automatically organise invoices and receipts — extract data, rename, sort, export CSV.",
        "category":     "automation",
        "subcategory":  "finance",
        "inputs":       ["invoices_folder", "output_format"],
        "outputs":      ["organised_invoices", "expenses_csv"],
        "execution_type": "hybrid",
        "dependencies": ["pillow", "pymupdf"],
        "trigger_keywords": [
            "invoice", "receipt", "tax preparation", "organize invoices",
            "expense report", "accounting", "invoice processing",
            "receipt organizer", "expense tracking", "financial documents",
        ],
        "agent_affinity": ["desktop", "coder"],
        "folder":       "invoice-organizer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "youtube-downloader",
        "name":         "YouTube — Video Downloader",
        "description":  "Download YouTube videos with customizable quality and format options. Supports various quality settings, multiple formats (mp4, webm, mkv), and audio-only downloads as MP3.",
        "category":     "automation",
        "subcategory":  "media",
        "inputs":       ["video_url", "quality", "format"],
        "outputs":      ["video_file", "audio_file"],
        "execution_type": "script",
        "dependencies": ["yt-dlp"],
        "trigger_keywords": [
            "download video", "youtube download", "video download",
            "download youtube", "save video", "yt-dlp", "download mp4",
            "download audio", "download mp3", "youtube to mp3",
            "youtube video",
        ],
        "agent_affinity": ["coder", "desktop"],
        "folder":       "video-downloader",
        "scripts":      ["scripts/download_video.py"],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "image-enhancer",
        "name":         "Image Enhancer",
        "description":  "Enhance images: upscale resolution, sharpen, reduce artifacts, optimize for web/print.",
        "category":     "automation",
        "subcategory":  "media",
        "inputs":       ["image_path", "target_resolution", "use_case"],
        "outputs":      ["enhanced_image"],
        "execution_type": "hybrid",
        "dependencies": ["pillow"],
        "trigger_keywords": [
            "enhance image", "upscale image", "improve image quality",
            "sharpen image", "image resolution", "fix image", "upscale photo",
            "improve photo quality", "image upscaling", "photo enhancement",
        ],
        "agent_affinity": ["coder", "desktop"],
        "folder":       "image-enhancer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── INTEGRATIONS / APIS ─────────────────────────
    {
        "id":           "connect",
        "name":         "Connect to Apps",
        "description":  "Connect Claude to 1000+ apps via Composio: email, Slack, GitHub, Notion, CRM, etc.",
        "category":     "integration",
        "subcategory":  "api",
        "inputs":       ["service_name", "action", "credentials"],
        "outputs":      ["action_result"],
        "execution_type": "hybrid",
        "dependencies": ["composio"],
        "trigger_keywords": [
            "send email gmail", "send slack message", "create github issue",
            "post discord", "update notion", "create jira ticket",
            "connect to", "integrate with", "send via", "post to slack",
            "github pull request", "send outlook email",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "connect",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "connect-apps",
        "name":         "Connect Apps Setup",
        "description":  "Setup guide and configuration for connecting Claude Code to external services via Composio.",
        "category":     "integration",
        "subcategory":  "setup",
        "inputs":       ["service_name"],
        "outputs":      ["setup_instructions", "configuration"],
        "execution_type": "prompt",
        "dependencies": ["composio"],
        "trigger_keywords": [
            "setup composio", "configure composio", "oauth setup",
            "api key setup", "connect apps setup", "composio configuration",
        ],
        "agent_affinity": ["skill"],
        "folder":       "connect-apps",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "composio-skills",
        "name":         "Composio 1000+ Service Skills",
        "description":  "Integration skills for 1000+ third-party services via Composio platform.",
        "category":     "integration",
        "subcategory":  "api",
        "inputs":       ["service", "action", "parameters"],
        "outputs":      ["service_response"],
        "execution_type": "hybrid",
        "dependencies": ["composio"],
        "trigger_keywords": [
            "composio", "third party api", "service integration",
            "use composio", "composio action", "automate service",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "composio-skills",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── DEVELOPMENT TOOLS ───────────────────────────
    {
        "id":           "mcp-builder",
        "name":         "MCP Server Builder",
        "description":  "Build Model Context Protocol servers in Python (FastMCP) or TypeScript.",
        "category":     "development",
        "subcategory":  "tooling",
        "inputs":       ["server_purpose", "tools_to_expose", "language"],
        "outputs":      ["mcp_server_code", "documentation"],
        "execution_type": "hybrid",
        "dependencies": ["python", "node"],
        "trigger_keywords": [
            "mcp server", "model context protocol", "build mcp",
            "create mcp", "claude plugin", "fastmcp", "mcp tool",
            "mcp resource", "expose tool", "mcp server python",
        ],
        "agent_affinity": ["coder"],
        "folder":       "mcp-builder",
        "scripts":      ["scripts/connections.py", "scripts/evaluation.py"],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "langsmith-fetch",
        "name":         "LangSmith Debugger",
        "description":  "Debug LangChain/LangGraph agents by fetching traces from LangSmith Studio.",
        "category":     "development",
        "subcategory":  "debugging",
        "inputs":       ["project_name", "run_id_or_filter"],
        "outputs":      ["trace_analysis", "error_report"],
        "execution_type": "hybrid",
        "dependencies": ["langsmith-fetch", "langsmith"],
        "trigger_keywords": [
            "langsmith", "langchain debug", "langgraph trace",
            "debug langchain", "agent trace", "langsmith studio",
            "execution trace", "langsmith run", "debug agent trace",
        ],
        "agent_affinity": ["coder"],
        "folder":       "langsmith-fetch",
        "scripts":      ["scripts/connections.py", "scripts/evaluation.py"],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "webapp-testing",
        "name":         "Web App Tester",
        "description":  "Test local web apps with Playwright: UI verification, screenshot capture, browser logs.",
        "category":     "development",
        "subcategory":  "testing",
        "inputs":       ["app_url", "test_scenarios"],
        "outputs":      ["test_results", "screenshots", "error_report"],
        "execution_type": "hybrid",
        "dependencies": ["playwright"],
        "trigger_keywords": [
            "test webapp", "test website", "browser testing", "playwright test",
            "ui testing", "frontend test", "web test", "test my app",
            "test the ui", "automated testing", "browser automation test",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "webapp-testing",
        "scripts":      [
            "scripts/with_server.py",
            "examples/console_logging.py",
            "examples/element_discovery.py",
        ],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "skill-creator",
        "name":         "Skill Creator",
        "description":  "Create new Claude skills with proper structure, validation, and packaging.",
        "category":     "development",
        "subcategory":  "meta",
        "inputs":       ["skill_name", "skill_purpose", "execution_type"],
        "outputs":      ["skill_folder", "skill_md", "validation_report"],
        "execution_type": "hybrid",
        "dependencies": ["python"],
        "trigger_keywords": [
            "create skill", "new skill", "build skill", "make skill",
            "skill template", "add skill", "define skill",
        ],
        "agent_affinity": ["coder", "skill"],
        "folder":       "skill-creator",
        "scripts":      [
            "scripts/init_skill.py",
            "scripts/package_skill.py",
            "scripts/quick_validate.py",
        ],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "developer-growth-analysis",
        "name":         "Developer Growth Analyzer",
        "description":  "Analyse coding patterns from chat history, identify learning gaps, send Slack report.",
        "category":     "development",
        "subcategory":  "analytics",
        "inputs":       ["chat_history_path", "slack_user"],
        "outputs":      ["growth_report", "learning_recommendations"],
        "execution_type": "hybrid",
        "dependencies": ["slack"],
        "trigger_keywords": [
            "developer growth", "coding patterns", "learning gaps",
            "hackernews recommendations", "growth report", "coding analysis",
            "developer analytics", "my coding habits",
        ],
        "agent_affinity": ["coder", "memory"],
        "folder":       "developer-growth-analysis",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── COMMUNICATION ───────────────────────────────
    {
        "id":           "internal-comms",
        "name":         "Internal Communications",
        "description":  "Write internal comms: 3P updates, newsletters, FAQs, incident reports, status updates.",
        "category":     "communication",
        "subcategory":  "writing",
        "inputs":       ["comm_type", "content_details", "audience"],
        "outputs":      ["communication_draft"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "internal communication", "company newsletter", "team update",
            "3p update", "status report", "leadership update",
            "incident report", "company-wide email", "team announcement",
            "internal email", "stakeholder update",
        ],
        "agent_affinity": ["content"],
        "folder":       "internal-comms",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "content-research-writer",
        "name":         "Content Research Writer",
        "description":  "Collaborative writing partner: outlines, research, hooks, voice preservation, multi-draft.",
        "category":     "communication",
        "subcategory":  "writing",
        "inputs":       ["topic", "audience", "format", "length"],
        "outputs":      ["article_draft", "outline", "research_notes"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "write article", "blog post", "content", "research and write",
            "outline", "essay", "research paper", "long form content",
            "content creation", "write blog", "draft article",
            "content strategy", "copywriting",
        ],
        "agent_affinity": ["content"],
        "folder":       "content-research-writer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "meeting-insights-analyzer",
        "name":         "Meeting Insights Analyzer",
        "description":  "Analyse meeting transcripts: communication patterns, speaking ratios, actionable feedback.",
        "category":     "communication",
        "subcategory":  "analysis",
        "inputs":       ["transcript_file_or_text"],
        "outputs":      ["insights_report", "action_items", "patterns"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "meeting", "transcript", "meeting analysis", "meeting notes",
            "communication patterns", "analyze meeting", "meeting transcript",
            "meeting insights", "what was discussed", "meeting summary",
        ],
        "agent_affinity": ["content", "memory"],
        "folder":       "meeting-insights-analyzer",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── DOCUMENTS ───────────────────────────────────
    {
        "id":           "docx",
        "name":         "DOCX — Word Documents",
        "description":  "Create, edit, and analyze Word documents with tracked changes, comments, and formatting preservation.",
        "category":     "documents",
        "subcategory":  "word",
        "inputs":       ["file_path", "content", "template"],
        "outputs":      ["docx_file", "extracted_text", "formatted_document"],
        "execution_type": "hybrid",
        "dependencies": ["python-docx"],
        "trigger_keywords": [
            "word document", "create docx", "edit docx", "docx file",
            "word doc", "office document", "tracked changes", "word processing",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "document-skills/docx",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "pdf",
        "name":         "PDF — Document Toolkit",
        "description":  "Create, merge, split, and extract from PDF documents. Fill forms, extract tables, and convert formats.",
        "category":     "documents",
        "subcategory":  "pdf",
        "inputs":       ["file_path", "content", "operation"],
        "outputs":      ["pdf_file", "extracted_text", "tables", "merged_pdf"],
        "execution_type": "hybrid",
        "dependencies": ["pymupdf", "reportlab"],
        "trigger_keywords": [
            "create pdf", "edit pdf", "merge pdf", "split pdf",
            "extract pdf", "pdf form", "fill pdf", "pdf text",
            "pdf table", "pymupdf",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "document-skills/pdf",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "pptx",
        "name":         "PPTX — Presentations",
        "description":  "Create, edit, and analyze PowerPoint presentations with layouts, speaker notes, and professional formatting.",
        "category":     "documents",
        "subcategory":  "presentation",
        "inputs":       ["file_path", "content", "template"],
        "outputs":      ["pptx_file", "slide_content", "presentation"],
        "execution_type": "hybrid",
        "dependencies": ["python-pptx"],
        "trigger_keywords": [
            "powerpoint", "create pptx", "presentation", "slides",
            "pptx file", "speaker notes", "slide deck", "ppt design",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "document-skills/pptx",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "xlsx",
        "name":         "XLSX — Spreadsheets",
        "description":  "Create, edit, and analyze Excel spreadsheets with formulas, formatting, charts, and data analysis.",
        "category":     "documents",
        "subcategory":  "spreadsheet",
        "inputs":       ["file_path", "data", "formulas"],
        "outputs":      ["xlsx_file", "analysis_results", "charts"],
        "execution_type": "hybrid",
        "dependencies": ["openpyxl"],
        "trigger_keywords": [
            "excel", "create xlsx", "spreadsheet", "xlsx file",
            "excel formula", "openpyxl", "data analysis excel", "csv to excel",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "document-skills/xlsx",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── SUPERPOWERS ──────────────────────────────────
    {
        "id":           "brainstorming",
        "name":         "Brainstorming",
        "description":  "Structured brainstorming and ideation for any problem or project.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["problem_or_idea", "context", "constraints"],
        "outputs":      ["idea_list", "evaluation_matrix"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "brainstorm", "ideate", "creative ideas", "brainstorm session",
            "generate ideas", "think of ideas", "brainstorming",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/brainstorming",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "writing-plans",
        "name":         "Writing Plans",
        "description":  "Create detailed implementation plans with step-by-step breakdowns.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["task_description", "requirements", "constraints"],
        "outputs":      ["implementation_plan", "step_list"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "write plan", "create plan", "implementation plan", "planning",
            "plan this", "make a plan", "writing plans",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/writing-plans",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "executing-plans",
        "name":         "Executing Plans",
        "description":  "Execute a pre-written implementation plan step by step with verification.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["plan_text", "codebase_context"],
        "outputs":      ["execution_result", "verification_report"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "execute plan", "implement plan", "follow plan", "carry out plan",
            "execute the plan", "implement the plan",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/executing-plans",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "verification-before-completion",
        "name":         "Verification Before Completion",
        "description":  "Verify implementation completeness and correctness before marking done.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["implementation_code", "original_requirements"],
        "outputs":      ["verification_report", "checklist_results"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "verify", "verification", "check completion", "verify done",
            "is it complete", "verify implementation",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/verification-before-completion",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "systematic-debugging",
        "name":         "Systematic Debugging",
        "description":  "Debug systematically using structured investigation methodology.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["error_description", "code_context", "expected_behavior"],
        "outputs":      ["root_cause", "fix_suggestion", "debugging_report"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "debug systematically", "systematic debugging", "find root cause",
            "investigate bug", "debug methodically",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/systematic-debugging",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "test-driven-development",
        "name":         "Test-Driven Development",
        "description":  "Write tests first, then implement code to pass them (TDD workflow).",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["feature_description", "requirements"],
        "outputs":      ["test_code", "implementation_code"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "tdd", "test driven", "write tests first", "test driven development",
            "red green refactor",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/test-driven-development",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "writing-skills",
        "name":         "Writing Skills",
        "description":  "Create well-structured Claude skills with proper SKILL.md format.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["skill_name", "skill_purpose", "execution_type"],
        "outputs":      ["skill_md", "skill_folder"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "write skill", "create skill", "skill writing", "make a skill",
            "skill structure",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/writing-skills",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "using-git-worktrees",
        "name":         "Using Git Worktrees",
        "description":  "Manage parallel development with git worktrees for isolated branches.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["branch_name", "task_description"],
        "outputs":      ["worktree_setup", "branch_info"],
        "execution_type": "prompt",
        "dependencies": ["git"],
        "trigger_keywords": [
            "worktree", "git worktree", "parallel branch", "worktree setup",
            "multiple branches",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/using-git-worktrees",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "using-superpowers",
        "name":         "Using Superpowers",
        "description":  "Meta-skill: discover and invoke the right Superpowers skill for any task.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["task_description"],
        "outputs":      ["skill_recommendation", "invocation_guide"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "superpowers", "which skill", "use superpowers", "superpowers guide",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/using-superpowers",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "dispatching-parallel-agents",
        "name":         "Dispatching Parallel Agents",
        "description":  "Spawn multiple sub-agents to work on independent tasks simultaneously.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["tasks_list", "context"],
        "outputs":      ["dispatched_tasks", "results_summary"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "dispatch agents", "parallel agents", "subagent", "multiple agents",
            "spawn agents", "dispatching",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/dispatching-parallel-agents",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "subagent-driven-development",
        "name":         "Subagent-Driven Development",
        "description":  "Drive development by dispatching focused sub-agents for each task area.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["project_description", "task_areas"],
        "outputs":      ["development_plan", "agent_assignments"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "subagent driven", "agent driven development", "divide and conquer",
            "subagent development",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/subagent-driven-development",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "requesting-code-review",
        "name":         "Requesting Code Review",
        "description":  "Request a structured code review with specific areas of focus.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["code_or_pr_url", "review_focus"],
        "outputs":      ["review_request", "review_checklist"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "request review", "code review request", "review my code",
            "requesting code review",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/requesting-code-review",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "receiving-code-review",
        "name":         "Receiving Code Review",
        "description":  "Process and act on code review feedback systematically.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["review_feedback", "code_context"],
        "outputs":      ["action_items", "improvement_plan"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "receive review", "code review feedback", "review feedback",
            "receiving code review", "address review comments",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/receiving-code-review",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "finishing-a-development-branch",
        "name":         "Finishing a Development Branch",
        "description":  "Properly close a development branch: tests, review, merge, cleanup.",
        "category":     "development",
        "subcategory":  "superpowers",
        "inputs":       ["branch_name", "completion_checklist"],
        "outputs":      ["merge_report", "cleanup_summary"],
        "execution_type": "prompt",
        "dependencies": ["git"],
        "trigger_keywords": [
            "finish branch", "close branch", "merge branch", "land branch",
            "finishing development",
        ],
        "agent_affinity": ["coder"],
        "folder":       "superpowers/finishing-a-development-branch",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    # ─────────────────────────── FRONTEND DESIGN ─────────────────────────────
    {
        "id":           "frontend-design",
        "name":         "Frontend Design",
        "description":  "Build elaborate multi-component frontends with React, Tailwind CSS, and shadcn/ui.",
        "category":     "content",
        "subcategory":  "frontend",
        "inputs":       ["design_description", "components", "styling_preferences"],
        "outputs":      ["html_artifact", "react_components"],
        "execution_type": "prompt",
        "dependencies": ["node", "npm"],
        "trigger_keywords": [
            "frontend design", "build frontend", "create ui", "design component",
            "react component", "tailwind", "shadcn", "web design",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "frontend-design",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    # ─────────────────────────── GSTACK ──────────────────────────────────────
    {
        "id":           "gstack-browse",
        "name":         "GStack Browse",
        "description":  "Browse websites with headless browser for testing and inspection.",
        "category":     "development",
        "subcategory":  "browser",
        "inputs":       ["url", "actions"],
        "outputs":      ["page_content", "screenshots"],
        "execution_type": "prompt",
        "dependencies": ["playwright"],
        "trigger_keywords": [
            "browse site", "browse website", "open url", "headless browser",
            "gstack browse", "visit page",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "gstack/browse",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-qa",
        "name":         "GStack QA",
        "description":  "Automated quality assurance testing for web apps and deployments.",
        "category":     "development",
        "subcategory":  "testing",
        "inputs":       ["target_url", "test_scenarios"],
        "outputs":      ["qa_report", "test_results"],
        "execution_type": "prompt",
        "dependencies": ["playwright"],
        "trigger_keywords": [
            "qa test", "quality assurance", "gstack qa", "test website",
            "automated testing", "qa check",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "gstack/qa",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-review",
        "name":         "GStack Review",
        "description":  "Code review and PR review using structured review methodology.",
        "category":     "development",
        "subcategory":  "review",
        "inputs":       ["code_or_pr", "review_focus"],
        "outputs":      ["review_report", "action_items"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "code review", "pr review", "gstack review", "review code",
            "review pull request",
        ],
        "agent_affinity": ["coder"],
        "folder":       "gstack/review",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-canary",
        "name":         "GStack Canary",
        "description":  "Canary deployment testing — verify features in production-like conditions.",
        "category":     "development",
        "subcategory":  "deployment",
        "inputs":       ["deployment_url", "feature_description"],
        "outputs":      ["canary_report", "verification_results"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "canary test", "canary deploy", "gstack canary", "canary deployment",
            "production test",
        ],
        "agent_affinity": ["coder"],
        "folder":       "gstack/canary",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-design-consultation",
        "name":         "GStack Design Consultation",
        "description":  "Expert design consultation for UI/UX decisions and design systems.",
        "category":     "content",
        "subcategory":  "design",
        "inputs":       ["design_question", "current_design"],
        "outputs":      ["consultation_report", "recommendations"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "design consultation", "ui consultation", "gstack design",
            "ux advice", "design review",
        ],
        "agent_affinity": ["content", "coder"],
        "folder":       "gstack/design-consultation",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-investigate",
        "name":         "GStack Investigate",
        "description":  "Systematic investigation of bugs, errors, or unexpected behavior.",
        "category":     "development",
        "subcategory":  "debugging",
        "inputs":       ["issue_description", "logs_or_context"],
        "outputs":      ["investigation_report", "root_cause"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "investigate", "gstack investigate", "investigate bug",
            "investigate error", "systematic investigation",
        ],
        "agent_affinity": ["coder"],
        "folder":       "gstack/investigate",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-ship",
        "name":         "GStack Ship",
        "description":  "Ship code to production with pre-deploy checks and verification.",
        "category":     "development",
        "subcategory":  "deployment",
        "inputs":       ["branch_or_commit", "deployment_target"],
        "outputs":      ["ship_report", "deployment_status"],
        "execution_type": "prompt",
        "dependencies": ["git"],
        "trigger_keywords": [
            "ship", "deploy", "gstack ship", "ship to production", "release",
            "land and deploy",
        ],
        "agent_affinity": ["coder"],
        "folder":       "gstack/ship",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "gstack-health",
        "name":         "GStack Health",
        "description":  "Check project health: dependencies, tests, linting, and code quality.",
        "category":     "development",
        "subcategory":  "maintenance",
        "inputs":       ["project_path", "health_checks"],
        "outputs":      ["health_report", "issues_list"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "health check", "project health", "gstack health", "check project",
            "codebase health",
        ],
        "agent_affinity": ["coder"],
        "folder":       "gstack/health",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    # ─────────────────────────── MCP INTEGRATION ─────────────────────────────
    {
        "id":           "context7-mcp",
        "name":         "Context7 Documentation Lookup",
        "description":  "Fetch up-to-date documentation for any library, framework, or API.",
        "category":     "integration",
        "subcategory":  "documentation",
        "inputs":       ["library_name", "query"],
        "outputs":      ["documentation", "code_examples"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "context7", "library docs", "documentation lookup", "api reference",
            "sdk documentation", "framework docs",
        ],
        "agent_affinity": ["coder"],
        "folder":       "context7-mcp",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "tavily-search",
        "name":         "Tavily Web Search",
        "description":  "Search the web for current information, research, and data.",
        "category":     "integration",
        "subcategory":  "research",
        "inputs":       ["search_query", "search_depth"],
        "outputs":      ["search_results", "summarized_answer"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "tavily", "web search", "search the web", "research online",
            "internet search", "find online",
        ],
        "agent_affinity": ["browser", "coder"],
        "folder":       "tavily",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },

    # ─────────────────────────── UTILITIES ───────────────────────────────────
    {
        "id":           "raffle-winner-picker",
        "name":         "Raffle Winner Picker",
        "description":  "Pick random winners from lists or spreadsheets using cryptographic randomness.",
        "category":     "utility",
        "subcategory":  "random",
        "inputs":       ["participants_list_or_file", "num_winners"],
        "outputs":      ["winners_list", "selection_certificate"],
        "execution_type": "prompt",
        "dependencies": [],
        "trigger_keywords": [
            "raffle", "random winner", "giveaway", "contest winner",
            "random selection", "draw winner", "lottery", "pick winner",
            "random draw", "sweepstakes",
        ],
        "agent_affinity": ["coder", "content"],
        "folder":       "raffle-winner-picker",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
    {
        "id":           "skill-share",
        "name":         "Skill Share",
        "description":  "Create and share skills — validate, package to zip, post to Slack.",
        "category":     "utility",
        "subcategory":  "meta",
        "inputs":       ["skill_folder", "slack_channel"],
        "outputs":      ["skill_zip", "slack_post"],
        "execution_type": "hybrid",
        "dependencies": ["slack"],
        "trigger_keywords": [
            "share skill", "publish skill", "distribute skill",
            "post skill", "skill zip", "package skill",
        ],
        "agent_affinity": ["skill", "coder"],
        "folder":       "skill-share",
        "scripts":      [],
        "has_context":  True,
        "active":       True,
    },
]

# Build quick-lookup dictionaries
SKILL_BY_ID: dict[str, dict] = {s["id"]: s for s in ALL_SKILLS}

SKILLS_BY_CATEGORY: dict[str, list[dict]] = {}
for _s in ALL_SKILLS:
    SKILLS_BY_CATEGORY.setdefault(_s["category"], []).append(_s)

SKILLS_BY_AGENT: dict[str, list[dict]] = {}
for _s in ALL_SKILLS:
    for _ag in _s["agent_affinity"]:
        SKILLS_BY_AGENT.setdefault(_ag, []).append(_s)
